### ISSUE TITLE
All implementations of Cost::gradient simply multiply a gradient by  gradient_error_by_coefficent

### ISSUE THREAD

**Issue by HolgerPeters** [blue-yonder/vikos#10]
All implementations of `Cost::gradient` simply multiply a gradient by  `gradient_error_by_coefficent`. I.e. with the currently implemented Cost functions, we could just drop the `gradient_error_by_coefficent` variable from the interface and let the caller of `Cost::gradient` multiply with such a value.

Of course, if it were to be expected that some implementations of the cost function would use that parameter in a non-multiplicative way, having it remain in the interface might be a reasonable choice.

**Comment by HolgerPeters** [comment]
`gradient_error_by_coefficent` seems to be the inner derivative (following the chain rule).  Thus, the multiplication by `gradient_error_by_coefficient` could indeed be generalized.

**Comment by pacman82** [comment]
fixed by #11
